name: ITHome Rank Daily to TG

on:
  workflow_dispatch:
  schedule:
    # UTC+8 ~ 07:33
    - cron: "33 23 * * *"

jobs:
  rank-daily:
    name: Rank Daily
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Get Daily Rank
        id: get-daily-rank
        shell: bash
        run: |
          node main.js

      - name: Telegram Notify
        if: ${{ always() && env.TELEGRAM_TOKEN && env.TELEGRAM_TO }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *IT之家日榜*

            ${{ steps.get-daily-rank.outputs.result  }}
